### ISSUE TITLE
Beta 14 Godot-Dlang fail to ~~build~~ not explode godot on linux.

### ISSUE THREAD

**Issue by SpiceyWolf** [godot-dlang/godot-dlang#69]
Ive recently installed to linux so this may be a linux specific issue i got no idea... i clean dumped from godot beta 14 extensions, and after trying to build the example code as before (i in fact cleaned my whole dub and ensured its grabbing master... there is no old borky version like my last post so I appologize for that time being a dummy post) and I get this error when it tries to build.

```
dub build godot-dlang

Building package godot-dlang in /home/spiceywolf/.dub/packages/godot-dlang-master/godot-dlang/

Starting Performing "debug" build using /usr/bin/dmd for x86_64.

Building godot-dlang ~master: building configuration [library]

../../../.dub/packages/godot-dlang-master/godot-dlang/src/godot/variant.d(489,49): Error: no property 'variant_as_vector3' for '_godot_api' of type 'godot.abi.gdextension.GDExtensionInterface*'

../../../.dub/packages/godot-dlang-master/godot-dlang/classes/godot/physicsdirectbodystate3dextension.d(113,13): Error: template instance 'godot.variant.Variant.as!(Vector3)' error instantiating

../../../.dub/packages/godot-dlang-master/godot-dlang/classes/godot/scriptextension.d(216,13): Error: returning 'ret.as()' escapes a reference to local variable 'ret'

Error /usr/bin/dmd failed with exit code 1.
```

I know we are about to get a release candidate build so this isn't something I expect to get any real work fixing til the RC support is just done directly... its moreso a "This may be a issue that is overlooked __if__ its not a linux specific issue" and Im looking at how to just work around this for now lol

Update: IF it does build properly on windows from clean setup, it is possibly a linux specific issue with (I assume) the generator... I had a buddy pull the extensions json from windows to ensure its not godot giving me a weird different file on linux vs windows or anything and i got identical error, even when running on the ~master from 2 commits ago (on beta 12) which I was able to build properly on windows from clean.

Update2: Ive been playing with it, Im actually thinking now its __mostly__ just weird quirks of DLang on linux? I got through alot of errors by simply modifying the `return ret.as(RefOrT(bla));` lines that are in there to `auto rr = ret.as(RefOrT(bla)); return rr;` though havent completed getting it to build as its still throwing a tantrum if Vector3 shows up in them... Still workin on figuring that one out.

Update3: I just made the vector3 things `return Vector3();` which got me to building... but the code loading into godot kinda crashes lol not sure if its the "implicit conversion of dstring to wstring" i casted away or if it was the 'fix' i did for the return complaints everywhere... i gotta go to bed though so no more time to play around and find out what causes the crash.

**Comment by Superbelko** [comment]
It is something with DMD and -dip1000 by default, it thinks it escapes scope, I will push "fix" ASAP

**Comment by Superbelko** [comment]
Try current master, it should fix this "escapes a reference to local variable" error.

Not sure about Vector3, haven't seen this one before (on Windows).

**Comment by SpiceyWolf** [comment]
Alright, ill give it a shot (maybe itll just fix itself lol)

**Comment by SpiceyWolf** [comment]
Nah, the vector 3 issue is still present but heres the exact error message:
```
../../../.dub/packages/godot-dlang-master/godot-dlang/src/godot/variant.d(489,49): Error: no property `variant_as_vector3` for `_godot_api` of type `godot.abi.gdextension.GDExtensionInterface*`
../../../.dub/packages/godot-dlang-master/godot-dlang/classes/godot/physicsdirectbodystate3dextension.d(113,13): Error: template instance `godot.variant.Variant.as!(Vector3)` error instantiating
```

**Comment by Superbelko** [comment]
Oh, this thing is ancient.

Could you try removing lines 482-500 in src/godot/variant.d? Just be careful with this else-if in there.

**Comment by SpiceyWolf** [comment]
That made the vector3 complaint go away (dunno if itll return later... but at least it didnt chain me 100x over first)

Finally just get this error which I probably was not correcting properly:
```
../../../.dub/packages/godot-dlang-master/godot-dlang/src/godot/api/register.d(275,39): Error: cannot implicitly convert expression `(v.as()).data()` of type `dstring` to `wstring`
../../../.dub/packages/godot-dlang-master/godot-dlang/src/godot/api/wrap.d(636,41): Error: cannot implicitly convert expression `(v.as()).data()` of type `dstring` to `wstring`
../../../.dub/packages/godot-dlang-master/godot-dlang/src/godot/api/register.d(183,21): Error: template instance `godot.api.register.register!(Greeter)` error instantiating
source/greeter.d(18,1):        parent scope from here: `mixin GodotNativeLibrary!("mydplugin", Greeter)`
```

**Comment by Superbelko** [comment]
I don't see anything wrong in code, 

__register.d:275__: String.data() returns wchar_t[], all ok
```d
wstring str = v.as!String.data();
```

Same with wrap.d:636.

Anyway I will look later when I got to do linux stuff.

**Comment by SpiceyWolf** [comment]
i casted to wstring and it crashes just loading the dll now xD BUT that is definitely the final error to getting the dlang stuff workin linux side (assuming nothing else is wildly broken)

**Comment by SpiceyWolf** [comment]
anyway, leavin for work ttyl

**Comment by Superbelko** [comment]
https://github.com/godot-dlang/godot-dlang/commit/5f32d787441f603eaeea95b08e20b4ade12a57d0 should fix this now, it still might crash on start because of broken ref counting triggering assert when ran without debugger.

**Comment by SpiceyWolf** [comment]
definitely gets the compile :P and definitely still crashes lol is that crash happening on windows too? or just linux side?

**Comment by Superbelko** [comment]
Needs to be checked with debugger.

I also noticed godot does something strange with node path and causes double freeing that triggers that assert, since we already disabled refcounting for NodePath this is not our issue but a godot one, it might be how we are using them or actually a godot bug. 
And it happens only with OnReady("some/node/path") properties.

**Comment by SpiceyWolf** [comment]
Well, its still crashing on beta 14, but not on 17 so i guess doesnt matter? XD You should be good to close this I guess (I won't do it in case you had anything else to document here or whatever)

**Comment by Superbelko** [comment]
That's amazing! They have different defaults in dumped API on Linux which has this new typed array defaults in beta17, but not on Windows.

**Comment by SpiceyWolf** [comment]
Works fine, I did a few small things it's no longer exploding -- no new immediate issues!
